### ISSUE TITLE
Create logo

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/design#1]
We need a logo, esp for favicon.

😢

**Comment by mirzazulfan** [comment]
Hi @108kb , @ri7nz I've designed a logo, what do you think guys? 
![EF](https://user-images.githubusercontent.com/36124339/56728330-bca44a80-677c-11e9-94e9-2e2664c33de3.png)

**Comment by r17x** [comment]
@mirzazulfan  Good job, It's Awesome Logo. 
Can you make it logo with Red Stroke & background white (logo right in a sample)?  
@108kb  how about you?

**Comment by faultables** [comment]
Cool! What if we hide this dot? Could you edit it just for a preview?

![Screen Shot 2019-04-25 at 22 14 03](https://user-images.githubusercontent.com/6561394/56747084-8cbe6c80-67a7-11e9-9a1d-b3babebb0b02.png)

**Comment by mirzazulfan** [comment]
Like this? I'll finalize the files. thanks guys :)
![EF 2](https://user-images.githubusercontent.com/36124339/56785224-68ea3d80-681e-11e9-836c-478abc349e92.png)

**Comment by r17x** [comment]
@108kb  how about you? I vote for the right 
![image](https://user-images.githubusercontent.com/16365952/56844950-846b4c00-68e3-11e9-9a69-985194e1ce56.png)

**Comment by faultables** [comment]
Yeah me too. Maybe we need bw version for this, right?

**Comment by mirzazulfan** [comment]
I agree with you guys. So what color and size do you prefer? I will send a variety of colors, sizes and logotypes.
![3EF](https://user-images.githubusercontent.com/36124339/56847526-30be2a00-6906-11e9-9c83-f5de1071536d.png)

**Comment by r17x** [comment]
@mirzazulfan  Super Awesome, I Think 💯 .
@108kb @alvinisasi   how about you?

**Comment by faultables** [comment]
Ship it 🚀

**Comment by r17x** [comment]
@mirzazulfan  we Recommended you to add the new logo in `READE.md` File below here
![image](https://user-images.githubusercontent.com/16365952/56851847-eeb0da80-693d-11e9-85b5-9e69ba3a1451.png)  with `title: New Logo`

**Comment by mirzazulfan** [comment]
Sure. Cool. I'll add it as soon as possible. :)

**Comment by mirzazulfan** [comment]
Hi guys, I've created a pr, #4 please check. If you need anything in the future, dont hesitate to contact me. Sukses selalu.

**Comment by faultables** [comment]
@mirzazulfan Thanks!

**Comment by faultables** [comment]
Look at me guys

![Screen Shot 2019-04-29 at 09 17 30](https://user-images.githubusercontent.com/6561394/56873879-c1f4e400-6a5f-11e9-8158-2ae375aef44a.png)

**Comment by r17x** [comment]
Thanks for everything @108kb  @mirzazulfan .

**Comment by mirzazulfan** [comment]
you're welcome guys. :)
